db:
  mongoDBHost: 127.0.0.1
  mongoDBName: pw02

runner:
  #  telegramServiceStartCommand: java -jar telegramService-1.0-SNAPSHOT.jar
  telegramServiceStartCommand:

connection:
  socketPort: 8001
  rabbitMqHost: localhost
  rabbitMqPort: 5672

mq:
  queueDataName: otpService

otp:
  expireMin: 5