db:
  mongoDBHost: 127.0.0.1
  mongoDBName: pw02

runner:
#  telegramServiceStartCommand: java -jar F:\\Documents\\java\\2019-09-otus-java-Emelyanov-project-work\\telegramService\\target\\telegramService-1.0-SNAPSHOT.jar
  telegramServiceStartCommand: java -jar C:\\Users\\d.yemelianov\\Documents\\java\\2019-09-otus-java-Emelyanov-project-work\\telegramService\\target\\telegramService-1.0-SNAPSHOT.jar

connection:
  socketPort: 8001
  rabbitMqHost: localhost
  rabbitMqPort: 5672

mq:
  queueDataName: otpService

otp:
  expireMin: 5